= ol.clave.issuers


Convenience ACME directory URLs for well-known certificate authorities.

Check each provider's documentation before use. Some providers require
External Account Binding (EAB), account setup, or payment.

Compatibility note: these URLs point to external services and may change or
disappear without a major version bump.

[#lets-encrypt-staging-ca]
== lets-encrypt-staging-ca





Let's Encrypt staging ACME directory URL.

See https://letsencrypt.org/docs/staging-environment/.

[.api-source]
link:https://github.com/outskirtslabs/clave/blob/main/src/ol/clave/issuers.clj#L10-L14[source,window=_blank]

'''

[#lets-encrypt-production-ca]
== lets-encrypt-production-ca





Let's Encrypt production ACME directory URL.

See https://letsencrypt.org/getting-started/.

[.api-source]
link:https://github.com/outskirtslabs/clave/blob/main/src/ol/clave/issuers.clj#L16-L20[source,window=_blank]

'''

[#zerossl-production-ca]
== zerossl-production-ca





ZeroSSL production ACME directory URL.

See https://zerossl.com/documentation/acme/.

[.api-source]
link:https://github.com/outskirtslabs/clave/blob/main/src/ol/clave/issuers.clj#L22-L26[source,window=_blank]

'''

[#google-trust-staging-ca]
== google-trust-staging-ca





Google Trust Services staging ACME directory URL.

See https://cloud.google.com/certificate-manager/docs/public-ca-tutorial.

[.api-source]
link:https://github.com/outskirtslabs/clave/blob/main/src/ol/clave/issuers.clj#L28-L32[source,window=_blank]

'''

[#google-trust-production-ca]
== google-trust-production-ca





Google Trust Services production ACME directory URL.

See https://cloud.google.com/certificate-manager/docs/public-ca-tutorial.

[.api-source]
link:https://github.com/outskirtslabs/clave/blob/main/src/ol/clave/issuers.clj#L34-L38[source,window=_blank]
